package com.example.lifetrack.api;

import android.os.Handler;
import android.os.Looper;
import com.example.lifetrack.data.entity.DailyHealthRecord;
import java.util.List;
import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class HealthRepository {

    private ApiService apiService;

    public HealthRepository() {
        // Initializes the Retrofit client
        apiService = ApiClient.getClient().create(ApiService.class);
    }

    public void getHealthAssessment(DailyHealthRecord record, final ApiCallback callback) {
        HealthDataRequest request = new HealthDataRequest(
                record.getDate(),
                record.getExerciseMinutes(),
                record.getSleepHours(),
                record.getFoodNote()
        );

        // Step 1: Upload raw data to the 'health_records' table
        apiService.sendHealthData(request).enqueue(new Callback<Void>() {
            @Override
            public void onResponse(Call<Void> call, Response<Void> response) {
                if (response.isSuccessful()) {
                    // Step 2: WAIT for the Supabase SQL Trigger to finish processing
                    // Increased to 2 seconds to avoid the "Assessment Pending" fallback
                    new Handler(Looper.getMainLooper()).postDelayed(() -> {
                        fetchCloudAssessment(record, callback);
                    }, 2000);
                } else {
                    // Falls back to local if the server rejects the upload (e.g., Code 400/500)
                    generateLocalAssessment(record, "Sync Error (" + response.code() + ")", callback);
                }
            }

            @Override
            public void onFailure(Call<Void> call, Throwable t) {
                // Falls back to local if there is no internet connection
                generateLocalAssessment(record, "Offline Mode", callback);
            }
        });
    }

    private void fetchCloudAssessment(DailyHealthRecord record, final ApiCallback callback) {
        // Step 3: Attempt to retrieve the AI-generated assessment from the cloud
        apiService.getLatestAssessment().enqueue(new Callback<List<HealthAssessmentResponse>>() {
            @Override
            public void onResponse(Call<List<HealthAssessmentResponse>> call, Response<List<HealthAssessmentResponse>> response) {
                if (response.isSuccessful() && response.body() != null && !response.body().isEmpty()) {
                    // Success: Return the actual result generated by the Supabase Cloud Trigger
                    callback.onSuccess(response.body().get(0), "Cloud AI Analysis");
                } else {
                    // Fallback: The cloud table is empty or the fetch returned no data
                    generateLocalAssessment(record, "Local Assessment (Cloud Pending)", callback);
                }
            }

            @Override
            public void onFailure(Call<List<HealthAssessmentResponse>> call, Throwable t) {
                generateLocalAssessment(record, "Offline Mode", callback);
            }
        });
    }

    private void generateLocalAssessment(DailyHealthRecord record, String sourceLabel, ApiCallback callback) {
        // Computational logic performed locally when the cloud is unavailable
        int score = 50; // Starting baseline
        if (record.getSleepHours() >= 7) score += 20;
        else if (record.getSleepHours() >= 5) score += 10;

        if (record.getExerciseMinutes() >= 30) score += 20;
        else if (record.getExerciseMinutes() >= 10) score += 10;

        if ("Healthy".equalsIgnoreCase(record.getFoodNote())) score += 10;
        else if ("Unhealthy".equalsIgnoreCase(record.getFoodNote())) score -= 10;

        // Ensure score remains within the 0-100 range
        score = Math.max(0, Math.min(score, 100));

        String status = (score >= 80) ? "Healthy" : (score >= 50) ? "Moderate" : "Unhealthy";

        String prediction = "Local Analysis: Your " + record.getExerciseMinutes() +
                "min activity suggests an improving cardiopulmonary trend. Sync for cloud insights.";

        HealthAssessmentResponse fallback = new HealthAssessmentResponse(
                record.getDate(), score, status, prediction
        );

        callback.onSuccess(fallback, sourceLabel);
    }

    public interface ApiCallback {
        // Passes the assessment and the source (Cloud vs Local) to the UI
        void onSuccess(HealthAssessmentResponse assessment, String source);
        void onError(String errorMessage);
    }
}